sudo: false

matrix:
  include:
    - os: linux
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-27.0.1
          - android-27
    - os: osx
      osx_image: xcode9.2
      language: java

jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yes | sdkmanager "platforms;android-27"; fi
      
install: true
      
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew android:build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew ios:build; fi